version: '3.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:example@localhost:5432/postgres?schema=public
    volumes:
      - ./backend:/server
      - /server/node_modules
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/var/lib/postgresql/data
volumes:
  data-volume:
